install.packages("devtools")
library(devtools)
install_github("Gibbsdavidl/CatterPlots")

library(CatterPlots)
x=c(1,2,3,4,5)
y=c(5,3,2,1,2)
catplot(x,y)
x1=c(9,8,7,4,2)
y1=c(1,4,5,4,6)
rainbowCats(x1,y1)
morecats(x,y)
morecats()
morecats(x)
multicat(x,y,catcolor = "pink")